name: 'Publish'

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Branch name
      run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: --all --target . --no-latest --version $TAG
